apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: smtx-lab-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: smtx-lab-agent
subjects:
  - kind: ServiceAccount
    name: smtx-lab-agent
    namespace: smtx-lab-system
