apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smtx-lab-operator
rules:
  - apiGroups: ["lab.smtx.io"]
    resources: ["networkprobelabs", "resourceanalyzerlabs"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["lab.smtx.io"]
    resources: ["networkprobelabs/status", "resourceanalyzerlabs/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["lab.smtx.io"]
    resources: ["networkprobelabs/finalizers", "resourceanalyzerlabs/finalizers"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "nodes", "namespaces", "configmaps", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "persistentvolumes", "resourcequotas", "limitranges", "replicationcontrollers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/metrics", "nodes/proxy"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments"]
    verbs: ["get", "list", "watch"]
